name: CraftCore
description: Craft Together plugin library
version: '${version}'
main: xyz.crafttogether.craftcore.CraftCore
api-version: 1.18

commands:
  verify:
    description: verify the linking of your discord account to your minecraft account
    usage: /<command> <code>
  unlink:
    description: Unlink your discord account from your minecraft account
    usage: /<command>
  spawn:
    description: Teleports you to spawn
    usage: /<command>
  setspawn:
    description: Sets the server world spawn
    usage: /<command>

permissions:
  craftcore.setspawn:
    description: Allows a player to set the server spawn
    default: false
  craftcore.spawn.skipwarmup:
    description: Allows a player to skip the spawn command warmup
    default: false
  craftcore.spawn:
    description: Teleports the player to spawn
    default: true